package:
  name: addict_yaml
  version: "0.2.7"

source:
 git_rev: v0.2.7
 git_url: https://github.com/jpn--/addict_yaml.git

requirements:
  build:
    - python
    - setuptools
    - addict
    - yaml
  run:
    - python
    - addict
    - yaml
  test:
    - python
    - addict
    - yaml

about:
  home: https://github.com/jpn--/addict_yaml
  license: MIT
  license_file: LICENSE