package:
  name: addict_yaml
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/jpn--/addict_yaml.git

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - conda-forge::addict
    - jpn::yamllint

test:
  imports:
    - addict_yaml

about:
  home: https://github.com/jpn--/addict_yaml
  license: MIT
  license_file: LICENSE.txt