package:
  name: addict_yaml
  version: "0.2.4"

source:
 git_rev: v0.2.4
 git_url: https://github.com/jpn--/addict_yaml.git

requirements:
  build:
    - python==3.6
    - setuptools
  run:
    - python==3.6
    - addict
    - yaml
  test:
    - python==3.6
    - addict
    - yaml

about:
  home: https://github.com/jpn--/addict_yaml
  license: MIT
  license_file: LICENSE