package:
  name: addict_yaml
  version: "0.2.0"

source:
  git_rev: v0.2.0
  git_url: https://github.com/jpn--/addict_yaml.git

channels:
  - jpn
  - defaults
  - bioconda
  - conda-forge

requirements:
  build:
    - python==3.6
    - setuptools
  run:
    - python==3.6
    - addict
    - pathspec
    - yamllint

test:
  imports:
    - addict_yaml

about:
  home: https://github.com/jpn--/addict_yaml
  license: MIT
  license_file: LICENSE.txt