package:
  name: addict_yaml
  version: "0.2.12"

source:
 git_rev: v0.2.12
 git_url: https://github.com/jpn--/addict_yaml.git

requirements:
  build:
    - python
    - setuptools
    - addict >=2.2
    - pyyaml
  run:
    - python
    - addict >=2.2
    - pyyaml
  test:
    - python
    - addict >=2.2
    - pyyaml

about:
  home: https://github.com/jpn--/addict_yaml
  license: MIT
  license_file: LICENSE